# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kawaii Programming
email: ammy_zmmn at hotmail dot com
email: zuimeng1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
<<<<<<< HEAD
  My personal blog with some programming projects.
baseurl: "http://computacion.cs.cinvestav.mx/~zmarquez" # the subpath of your site, e.g. /blog
url: "http://computacion.cs.cinvestav.mx/" # the base hostname & protocol for your site
github_username:  TsukiZombina
=======
  A profolio for an artical programmer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  Adagio-cantabile
>>>>>>> parent of 0371288... Modified

# Gems settings
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5